name: entrez-direct
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2025.8.3
  - entrez-direct=24.0
  - libasprintf=0.25.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.25.1
  - libgomp=15.1.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libstdcxx=15.1.0
  - libunistring=0.9.10
  - libzlib=1.3.1
  - openssl=3.5.4
  - wget=1.21.4
  - zlib=1.3.1
prefix: /home/marco/miniconda3/envs/entrez-direct
